language: r
sudo: required
warnings_are_errors: false
cache:
  directories: $TRAVIS_BUILD_DIR/packrat/
  packages: true
r_packages:
  - rmarkdown  

install:
  - R -e "0" --args --bootstrap-packrat
apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev
 - libcurl3
r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual
